//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryRecord
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string Sector { get; set; }
        public string Component { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public string District { get; set; }
        public string Village { get; set; }
        public string BeneficiaryName { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MaritalStatus { get; set; }
        public string TazkiraOrPassportNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Education { get; set; }
        public string HouseHoldStatus { get; set; }
        public string DisabilityStatus { get; set; }
        public string EconomicStatus { get; set; }
    }
}
