//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiariesRecord
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Disability { get; set; }
        public string Gender { get; set; }
        public string Month { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public System.Guid FlexibleInterventionsId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string AgeGroup { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
    }
}
