//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryBasicProjectData
    {
        public System.Guid Id { get; set; }
        [Display(Name = "Username")]
        public string UserName { get; set; }
        public string Roll { get; set; }
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
        public string Country { get; set; }
        [Display(Name = "Project Location")]

        public string ProjectLocation { get; set; }
        [Display(Name = "Type of Project")]

        public string TypeOfProject { get; set; }
        [Display(Name = "Seasonal Project Type")]

        public string SeasonalProjectType { get; set; }

        public string Name { get; set; }
        [Display(Name = "Number of Donars")]
        public Nullable<int> IsOneDonar { get; set; }
        [Display(Name = "IRW Project Pin Code")]

        public string IRWProjectPinCode { get; set; }
        [Display(Name = "Donar Partners")]
        [DataType(DataType.MultilineText)]

        public string Donar_Partner { get; set; }
        public string Duration { get; set; }
        [Display(Name = "Implementation Period From")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ImplementationPeriodFrom { get; set; }
        [Display(Name = "Implementation Period To")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ImplementationPeriodTo { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Display(Name = "Primary Sector")]
        public string PrimarySector { get; set; }
        [Display(Name = "Scope Of Project")]

        public string ScopeOfProject { get; set; }
        [Display(Name = "SDG Goal Indicator")]
        [DataType(DataType.MultilineText)]

        public string SDGGoalIndicator { get; set; }
        [Display(Name = "Direct Right Holders")]

        public Nullable<int> DirectRightHolders { get; set; }
    }
}
