//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountrySustainableDevelopmentGoalInformation
    {
        public System.Guid Id { get; set; }
        public string SustainableDevelopmentGoal_s_Alignment { get; set; }
        public int SDGGoal1Indicator { get; set; }
        public int SDGGoal2Indicator { get; set; }
        public int SDGGoal3Indicator { get; set; }
        public int SDGGoal4Indicator { get; set; }
        public int SDGGoal5Indicator { get; set; }
        public int SDGGoal6Indicator { get; set; }
        public int SDGGoal7Indicator { get; set; }
        public int SDGGoal8Indicator { get; set; }
        public int SDGGoal9Indicator { get; set; }
        public int SDGGoal10Indicator { get; set; }
        public int SDGGoal11Indicator { get; set; }
        public int SDGGoal12Indicator { get; set; }
        public int SDGGoal13Indicator { get; set; }
        public int SDGGoal14Indicator { get; set; }
        public int SDGGoal15Indicator { get; set; }
        public int SDGGoal16Indicator { get; set; }
        public int SDGGoal17Indicator { get; set; }
        public string CommunityType_HostCommunity_Local_Community_InternallyDisplacedPersons_IDPs__Refugees_ { get; set; }
    }
}
