//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryProjectSectorInformation
    {
        public System.Guid Id { get; set; }
        public string PrimarySector { get; set; }
        public int PrimarySectorTypeofCashProgrammingUnconditionalCash { get; set; }
        public int PrimarySectorTypeofCashProgrammingConditionalCash { get; set; }
        public int PrimarySectorTypeofCashProgrammingUnconditionalVouchers { get; set; }
        public int PrimarySectorTypeofCashProgrammingConditionalVouchers { get; set; }
        public int AdditionalSector_s__Shelter { get; set; }
        public int AdditionalSector_s__FoodDistribution { get; set; }
        public int AdditionalSector_s__NonFoodItemDistribution { get; set; }
        public int AdditionalSector_s__Cash_Programming { get; set; }
        public int AdditionalSector_s__Education { get; set; }
        public int AdditionalSector_s__CommunityPeaceBuilding { get; set; }
        public int AdditionalSector_s__FoodSecurity_Livelihoods { get; set; }
        public int AdditionalSector_s__Protection_Inclusion_Gender_Age_Disability_ { get; set; }
        public int AdditionalSector_s__ClimateChangeAdaptation { get; set; }
        public int AdditionalSector_s__Health { get; set; }
        public int AdditionalSector_s__WASH { get; set; }
        public int AdditionalSector_s__DisasterRiskReduction_DRR_ { get; set; }
        public int AdditionalSector_s__Microfinance { get; set; }
        public int AdditionalSector_s__Qurbani { get; set; }
        public int AdditionalSector_s__Ramadan { get; set; }
        public int AdditionalSector_s__Winterisation { get; set; }
        public int AdditionalSector_s__OrphanSponsorship { get; set; }
        public int AdditionalSector_s__Advocacy { get; set; }
        public int AdditionalSector_s__Other { get; set; }
        public int AdditionalSector_s__Safeguarding { get; set; }
        public int AdditionalSectorTypeofCashProgrammingUnconditionalCash { get; set; }
        public int AdditionalSectorTypeofCashProgrammingConditionalCash { get; set; }
        public int AdditionalSectorTypeofCashProgrammingUnconditionalVouchers { get; set; }
        public int AdditionalSectorTypeofCashProgrammingConditionalVouchers { get; set; }
        public string Would_you_classify_your_project_as_a_Graduation_Model_Project_ { get; set; }
        public int CrosscuttingThemeClimateChange { get; set; }
        public int CrosscuttingThemeWomen_sEmpowerment { get; set; }
        public int CrosscuttingThemeProtectionMainstreaming { get; set; }
        public int Cross_cuttingThemeInclusionofPersonsWithDisabilities { get; set; }
        public int CrosscuttingThemeInclusionofOlderPersons { get; set; }
        public int CrosscuttingThemeNone { get; set; }
    }
}
