//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IR_Admin.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlexibleIntervention
    {
        public System.Guid Id { get; set; }
        [DataType(DataType.MultilineText)]
        public string Fields { get; set; }
        [DataType(DataType.MultilineText)]

        public string Values { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string FilePath { get; set; }
    }
}
