//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Admin.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IR_Admin.Helpers.ProjectResource", typeof(ProjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST COMMUNITY / LOCAL COMMUNITY - FEMALES - WITH DISABILITIES.
        /// </summary>
        internal static string HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST COMMUNITY / LOCAL COMMUNITY - FEMALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST COMMUNITY / LOCAL COMMUNITY - MALES - WITH DISABILITIES.
        /// </summary>
        internal static string HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST COMMUNITY / LOCAL COMMUNITY - MALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNALLY DISPLACED PERSONS (IDPS) - FEMALES - WITH DISABILITIES.
        /// </summary>
        internal static string INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNALLY DISPLACED PERSONS (IDPS) - FEMALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNALLY DISPLACED PERSONS (IDPS) - MALES - WITH DISABILITIES.
        /// </summary>
        internal static string INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNALLY DISPLACED PERSONS (IDPS) - MALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUGEES - FEMALES - WITH DISABILITIES.
        /// </summary>
        internal static string REFUGEES_FEMALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("REFUGEES_FEMALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUGEES - FEMALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string REFUGEES_FEMALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("REFUGEES_FEMALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUGEES - MALES - WITH DISABILITIES.
        /// </summary>
        internal static string REFUGEES_MALES_WITH_DISABILITIES {
            get {
                return ResourceManager.GetString("REFUGEES_MALES_WITH_DISABILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUGEES - MALES - WITHOUT DISABILITIES.
        /// </summary>
        internal static string REFUGEES_MALES_WITHOUT_DISABILITIES {
            get {
                return ResourceManager.GetString("REFUGEES_MALES_WITHOUT_DISABILITIES", resourceCulture);
            }
        }
    }
}
