namespace IR_Admin.Helpers
{
    public enum ProjectEnums
    {
        HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITH_DISABILITIES=1,
        HOST_COMMUNITY_LOCAL_COMMUNITY_FEMALES_WITHOUT_DISABILITIES,
        HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITH_DISABILITIES,
        HOST_COMMUNITY_LOCAL_COMMUNITY_MALES_WITHOUT_DISABILITIES,
        INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITH_DISABILITIES,
        INTERNALLY_DISPLACED_PERSONS_IDPS_FEMALES_WITHOUT_DISABILITIES,
        INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITH_DISABILITIES,
        INTERNALLY_DISPLACED_PERSONS_IDPS_MALES_WITHOUT_DISABILITIES,
        REFUGEES_FEMALES_WITH_DISABILITIES,
        REFUGEES_FEMALES_WITHOUT_DISABILITIES,
        REFUGEES_MALES_WITH_DISABILITIES,
        REFUGEES_MALES_WITHOUT_DISABILITIES
    }

    public enum Disability
    {
        WithDisability,
        WithoutDisability
    }

    public enum Gender
    {
        Male,Female
    }
}